// <auto-generated />
using System;
using KocaYusuf_Telemetri.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KocaYusuf_Telemetri.Migrations
{
    [DbContext(typeof(MakineContext))]
    [Migration("20260822091351_DT5000_Eklendi")]
    partial class DT5000_Eklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.Alarm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("AlarmMesaji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("MakineID")
                        .HasColumnType("int");

                    b.Property<int?>("SureDakika")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MakineID");

                    b.ToTable("Alarmlar");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.IletisimMesaji", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GonderimZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("IletisimMesajlari");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.Makine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakineAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakineNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Makineler");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.MakineVerisi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double?>("AnaHavaBasinci")
                        .HasColumnType("float");

                    b.Property<double?>("AraHavaBasinci")
                        .HasColumnType("float");

                    b.Property<double?>("BalonSicakligi")
                        .HasColumnType("float");

                    b.Property<double?>("DT1000_HidrolikRaw")
                        .HasColumnType("float");

                    b.Property<double?>("DT1001_HavaRaw")
                        .HasColumnType("float");

                    b.Property<double?>("DT1002_AraHavaRaw")
                        .HasColumnType("float");

                    b.Property<double?>("DT110_HidrolikBasincHMI")
                        .HasColumnType("float");

                    b.Property<double?>("DT112_AnaHavaBasinciHMI")
                        .HasColumnType("float");

                    b.Property<double?>("DT212_AraHavaBasinciHMI")
                        .HasColumnType("float");

                    b.Property<double?>("DT32538_PresSicaklikSet")
                        .HasColumnType("float");

                    b.Property<double?>("DT32539_PresSicaklikHisterezis")
                        .HasColumnType("float");

                    b.Property<int?>("DT5000_VeriYapisiVersiyonu")
                        .HasColumnType("int");

                    b.Property<int?>("DT5001_MakineDurumu")
                        .HasColumnType("int");

                    b.Property<int?>("DT5002_ManuelOtomatik")
                        .HasColumnType("int");

                    b.Property<int?>("DT5003_AktifIslemAdimi")
                        .HasColumnType("int");

                    b.Property<int?>("DT5010_SonCevrimSuresi")
                        .HasColumnType("int");

                    b.Property<int?>("DT5011_AktifAlarmKodu")
                        .HasColumnType("int");

                    b.Property<int?>("DT5012_AlarmBitMaskesi1")
                        .HasColumnType("int");

                    b.Property<int?>("DT5013_AlarmBitMaskesi2")
                        .HasColumnType("int");

                    b.Property<int?>("DT5014_PLCHeartbeat")
                        .HasColumnType("int");

                    b.Property<int?>("DT5015_ProgramVersiyonu")
                        .HasColumnType("int");

                    b.Property<int?>("DT60_IstenenHMIMesaji")
                        .HasColumnType("int");

                    b.Property<int?>("DT61_MevcutHMISayfasi")
                        .HasColumnType("int");

                    b.Property<int?>("GenelDurum")
                        .HasColumnType("int");

                    b.Property<int?>("GenelDurumKodu")
                        .HasColumnType("int");

                    b.Property<double?>("HidrolikBasinc")
                        .HasColumnType("float");

                    b.Property<DateTime?>("KayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("MakineID")
                        .HasColumnType("int");

                    b.Property<double?>("PresSicakligi")
                        .HasColumnType("float");

                    b.Property<bool?>("R135_TermikAtti")
                        .HasColumnType("bit");

                    b.Property<bool?>("R16_CevrimAktif")
                        .HasColumnType("bit");

                    b.Property<bool?>("R2485_CalismaTipi1")
                        .HasColumnType("bit");

                    b.Property<bool?>("R2486_CalismaTipi2")
                        .HasColumnType("bit");

                    b.Property<bool?>("R2487_CalismaTipi3")
                        .HasColumnType("bit");

                    b.Property<bool?>("R248A_ProsesSarti")
                        .HasColumnType("bit");

                    b.Property<bool?>("R300_ManuelMod")
                        .HasColumnType("bit");

                    b.Property<bool?>("R301_OtomatikMod")
                        .HasColumnType("bit");

                    b.Property<bool?>("R32_GenelHata")
                        .HasColumnType("bit");

                    b.Property<bool?>("R36_CevrimTamamlandi")
                        .HasColumnType("bit");

                    b.Property<bool?>("R5_MakineCalisiyor")
                        .HasColumnType("bit");

                    b.Property<bool?>("R7_MakineHazir")
                        .HasColumnType("bit");

                    b.Property<bool?>("R98_AcilStopHafizasi")
                        .HasColumnType("bit");

                    b.Property<bool?>("R9D_OranFazla")
                        .HasColumnType("bit");

                    b.Property<bool?>("R9E_GenelHata2")
                        .HasColumnType("bit");

                    b.Property<int?>("UretimAdedi")
                        .HasColumnType("int");

                    b.Property<bool?>("X0_StartButonu")
                        .HasColumnType("bit");

                    b.Property<bool?>("X1_StopButonu")
                        .HasColumnType("bit");

                    b.Property<bool?>("X2_HazirSwitch")
                        .HasColumnType("bit");

                    b.Property<bool?>("X4_AcilStop")
                        .HasColumnType("bit");

                    b.Property<bool?>("X60_Vakostat")
                        .HasColumnType("bit");

                    b.Property<bool?>("X6_SonSwitch")
                        .HasColumnType("bit");

                    b.Property<bool?>("X8_YagMotoruTermik")
                        .HasColumnType("bit");

                    b.Property<bool?>("X9_BasincMotoruTermik")
                        .HasColumnType("bit");

                    b.Property<bool?>("XA_VakumMotoruTermik")
                        .HasColumnType("bit");

                    b.Property<bool?>("Y1_HidrolikBasincMotoru")
                        .HasColumnType("bit");

                    b.Property<bool?>("Y2_SolenoidValfS1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Y3_SolenoidValfS2")
                        .HasColumnType("bit");

                    b.Property<bool?>("Y4_SolenoidValfS3")
                        .HasColumnType("bit");

                    b.Property<bool?>("Y60_VakumPompasi")
                        .HasColumnType("bit");

                    b.Property<bool?>("Y61_YagSirkulasyonPompasi")
                        .HasColumnType("bit");

                    b.Property<bool?>("Y62_YagIsitici")
                        .HasColumnType("bit");

                    b.Property<bool?>("Y63_HavaIsitici")
                        .HasColumnType("bit");

                    b.Property<bool?>("Y64_SolenoidValfS16")
                        .HasColumnType("bit");

                    b.Property<bool?>("YC_SolenoidValfS11")
                        .HasColumnType("bit");

                    b.Property<bool?>("YD_SolenoidValfS12")
                        .HasColumnType("bit");

                    b.Property<bool?>("YE_SolenoidValfS13")
                        .HasColumnType("bit");

                    b.Property<bool?>("YF_SolenoidValfS14")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("MakineID");

                    b.ToTable("MakineVerileri");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.Alarm", b =>
                {
                    b.HasOne("KocaYusuf_Telemetri.Models.Makine", "Makine")
                        .WithMany("Alarmlar")
                        .HasForeignKey("MakineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makine");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.MakineVerisi", b =>
                {
                    b.HasOne("KocaYusuf_Telemetri.Models.Makine", "Makine")
                        .WithMany("Veriler")
                        .HasForeignKey("MakineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makine");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.Makine", b =>
                {
                    b.Navigation("Alarmlar");

                    b.Navigation("Veriler");
                });
#pragma warning restore 612, 618
        }
    }
}
