// <auto-generated />
using System;
using KocaYusuf_Telemetri.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KocaYusuf_Telemetri.Migrations
{
    [DbContext(typeof(MakineContext))]
    [Migration("20260722075702_UretimAdediEklendi")]
    partial class UretimAdediEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.Alarm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("AlarmMesaji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("MakineID")
                        .HasColumnType("int");

                    b.Property<int?>("SureDakika")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MakineID");

                    b.ToTable("Alarmlar");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.IletisimMesaji", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GonderimZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("IletisimMesajlari");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.Makine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakineAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakineNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Makineler");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.MakineVerisi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AnaHavaBasinci")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AraHavaBasinci")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AraHavaEkranDegeri")
                        .HasColumnType("int");

                    b.Property<decimal>("BalonSicakligi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalonSicaklikSet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GenelDurum")
                        .HasColumnType("int");

                    b.Property<int>("HavaEkranDegeri")
                        .HasColumnType("int");

                    b.Property<decimal>("HidrolikBasinc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HidrolikEkranDegeri")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("MakineID")
                        .HasColumnType("int");

                    b.Property<decimal>("PresSicakligi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PresSicaklikSet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UretimAdedi")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MakineID");

                    b.ToTable("MakineVerileri");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.Alarm", b =>
                {
                    b.HasOne("KocaYusuf_Telemetri.Models.Makine", "Makine")
                        .WithMany("Alarmlar")
                        .HasForeignKey("MakineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makine");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.MakineVerisi", b =>
                {
                    b.HasOne("KocaYusuf_Telemetri.Models.Makine", "Makine")
                        .WithMany("Veriler")
                        .HasForeignKey("MakineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makine");
                });

            modelBuilder.Entity("KocaYusuf_Telemetri.Models.Makine", b =>
                {
                    b.Navigation("Alarmlar");

                    b.Navigation("Veriler");
                });
#pragma warning restore 612, 618
        }
    }
}
